export default [
  {
    id: 1,
    img: {
      src: "https://scrimba.com/links/travel-journal-japan-image-url",
      alt: "Mount Fuji",
    },
    title: "Mount Fuji",
    country: "Japan",
    googleMapsLink: "https://maps.app.goo.gl/6RLYZDuuuqJ7kNGZ9",
    dates: "12 Jan, 2021 - 24 Jan, 2021",
    text: "Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.",
  },
  {
    id: 2,
    img: {
      src: "https://scrimba.com/links/travel-journal-australia-image-url",
      alt: "Sydney Opera House",
    },
    title: "Sydney Opera House",
    country: "Australia",
    googleMapsLink: "https://maps.app.goo.gl/Zr17SCrsJeCEKMd36",
    dates: "27 May, 2021 - 8 Jun, 2021",
    text: "The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of the Sydney Harbour, it is often regarded as one of the 20th century's most famous and distinctive buildings.",
  },
  {
    id: 3,
    img: {
      src: "https://scrimba.com/links/travel-journal-norway-image-url",
      alt: "Geirangerfjord",
    },
    title: "Geirangerfjord",
    country: "Norway",
    googleMapsLink: "https://maps.app.goo.gl/fhkJuBhmFDv47tiB7",
    dates: "01 Oct, 2021 - 18 Nov, 2021",
    text: "The Geiranger Fjord is a fjord in the Sunnmøre region of Møre og Romsdal county, Norway. It is located entirely in the Stranda Municipality.",
  },
  {
    id: 4,
    img: {
      src: "https://upload.wikimedia.org/wikipedia/commons/d/de/Colosseo_2020.jpg",
      alt: "Colosseum",
    },
    title: "Colosseum",
    country: "Italy",
    googleMapsLink: "https://maps.app.goo.gl/5J4X9yFq7VnRZJvRA",
    dates: "15 Mar, 2022 - 22 Mar, 2022",
    text: "The Colosseum is an oval amphitheatre in the centre of Rome, Italy. It is the largest ancient amphitheatre ever built, and is still the largest standing amphitheatre in the world today.",
  },
  {
    id: 5,
    img: {
      src: "https://images.unsplash.com/photo-1526397751294-331021109fbd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
      alt: "Machu Picchu",
    },
    title: "Machu Picchu",
    country: "Peru",
    googleMapsLink: "https://maps.app.goo.gl/QYspDmJvV7vVvZ5b8",
    dates: "05 Jul, 2022 - 12 Jul, 2022",
    text: "Machu Picchu is a 15th-century Inca citadel located in the Eastern Cordillera of southern Peru on a mountain ridge 2,430 meters (7,970 ft) above sea level.",
  },
  {
    id: 6,
    img: {
      src: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Kheops-Pyramid.jpg",
      alt: "Great Pyramid of Giza",
    },
    title: "Great Pyramid of Giza",
    country: "Egypt",
    googleMapsLink: "https://maps.app.goo.gl/4KJ7zZ8Z8Z8Z8Z8Z8",
    dates: "10 Nov, 2022 - 17 Nov, 2022",
    text: "The Great Pyramid of Giza is the oldest and largest of the three pyramids in the Giza pyramid complex bordering present-day Giza in Greater Cairo, Egypt.",
  },
  {
    id: 7,
    img: {
      src: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
      alt: "Grand Canyon",
    },
    title: "Grand Canyon",
    country: "USA",
    googleMapsLink: "https://maps.app.goo.gl/9J4X9yFq7VnRZJvRA",
    dates: "03 Apr, 2023 - 10 Apr, 2023",
    text: "The Grand Canyon is a steep-sided canyon carved by the Colorado River in Arizona, United States. It is contained within and managed by Grand Canyon National Park.",
  },
  {
    id: 8,
    img: {
      src: "https://images.unsplash.com/photo-1431274172761-fca41d930114?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
      alt: "Eiffel Tower",
    },
    title: "Eiffel Tower",
    country: "France",
    googleMapsLink: "https://maps.app.goo.gl/7KJ7zZ8Z8Z8Z8Z8Z8",
    dates: "22 May, 2023 - 29 May, 2023",
    text: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower.",
  },
  {
    id: 9,
    img: {
      src: "https://images.unsplash.com/photo-1694945463684-9c94d5294bae?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      alt: "Christ the Redeemer",
    },
    title: "Christ the Redeemer",
    country: "Brazil",
    googleMapsLink: "https://maps.app.goo.gl/8J4X9yFq7VnRZJvRA",
    dates: "12 Aug, 2023 - 19 Aug, 2023",
    text: "Christ the Redeemer is an Art Deco statue of Jesus Christ in Rio de Janeiro, Brazil, created by French sculptor Paul Landowski and built by Brazilian engineer Heitor da Silva Costa.",
  },
  {
    id: 10,
    img: {
      src: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
      alt: "Stonehenge",
    },
    title: "Stonehenge",
    country: "United Kingdom",
    googleMapsLink: "https://maps.app.goo.gl/9KJ7zZ8Z8Z8Z8Z8Z8",
    dates: "07 Oct, 2023 - 14 Oct, 2023",
    text: "Stonehenge is a prehistoric monument in Wiltshire, England, consisting of a ring of standing stones, each around 13 feet high, seven feet wide, and weighing around 25 tons.",
  },
];
